# Generated by Django 2.1.1 on 2018-09-17 03:04

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('skills', models.CharField(choices=[('J', 'Java'), ('P', 'Python'), ('A', 'Angular'), ('C', 'CPython'), ('C#', 'CpPython'), ('C++', 'C++Python')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
